# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityType',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('qname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.QuantityType')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('rtitle', models.CharField(max_length=100)),
                ('rdescription', models.CharField(max_length=500)),
                ('userid', models.IntegerField()),
                ('prep_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdescription', models.CharField(max_length=1000)),
                ('sorder', models.CharField(max_length=25)),
                ('prep_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprep_time', to='recipes.Recipes')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srid', to='recipes.Recipes')),
            ],
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipes'),
        ),
    ]
