# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('serid', models.IntegerField()),
                ('prep_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('order', models.CharField(max_length=25)),
                ('prep_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprep_time', to='recipes.Recipe')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srid', to='recipes.Recipe')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='quantity_type',
        ),
        migrations.RemoveField(
            model_name='recipeingredients',
            name='rid',
        ),
        migrations.RemoveField(
            model_name='recipesteps',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='recipesteps',
            name='rid',
        ),
        migrations.RenameField(
            model_name='quantitytype',
            old_name='qname',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='RecipeSteps',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='quantity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.QuantityType'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='rid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
    ]
