# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20161118_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='rid',
            new_name='recipe',
        ),
        migrations.RemoveField(
            model_name='step',
            name='prep_time',
        ),
        migrations.RemoveField(
            model_name='step',
            name='rid',
        ),
        migrations.AddField(
            model_name='step',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
            preserve_default=False,
        ),
    ]
