# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20161118_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='recipe',
            new_name='rid',
        ),
    ]
