# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20161119_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.IntegerField(),
        ),
    ]
