# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20161124_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='timestamp',
            new_name='createtime',
        ),
    ]
