# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20161125_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.FloatField(),
        ),
    ]
