# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20161126_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_pic',
        ),
    ]
