# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_recipe_recipe_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_pic',
            field=models.ImageField(null=True, upload_to='static/recipes/images/'),
        ),
    ]
