# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_auto_20161126_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_pic',
            field=models.FileField(blank=True, null=True, upload_to='recipes/static/recipes/images/'),
        ),
    ]
