# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20161125_0411'),
        ('recipes', '0025_auto_20161126_0810'),
    ]

    operations = [
    ]
