# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_merge_20161127_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
