# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_auto_20161127_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_pic',
            field=models.FileField(blank=True, null=True, upload_to='static/recipes/images/'),
        ),
    ]
