# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_auto_20161128_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
    ]
