# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_auto_20161127_0405'),
        ('recipes', '0029_remove_recipe_categories'),
    ]

    operations = [
    ]
