# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_auto_20161127_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_pic',
            field=models.FileField(blank=True, null=True, upload_to=recipes.models.get_file_path),
        ),
    ]
