# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_auto_20161129_2138'),
        ('recipes', '0030_merge_20161130_0139'),
    ]

    operations = [
    ]
